"""
Vrompt — PDF 리포트 생성기

스캔 결과를 하나의 PDF 파일로 출력.
한글 폰트(Malgun Gothic) 지원.
"""

import os
import warnings
from datetime import datetime
from typing import List, Dict
from fpdf import FPDF

from probes import ProbeResult

# ── FontTools 폰트 경고 숨기기 ──
warnings.filterwarnings(
    "ignore",
    message="MERG NOT subset; don't know how to subset; dropped",
    category=UserWarning
)

# ── 카테고리 이름 (이모지 제거 — PDF에서 깨짐 방지) ──
CATEGORY_NAMES_PDF = {
    "jailbreak": "[탈옥] Jailbreak",
    "unethical": "[비윤리] 비윤리적 발언",
    "prompt_injection": "[인젝션] 프롬프트 인젝션",
    "data_leakage": "[유출] 데이터 유출",
    "encoding": "[인코딩] 인코딩 우회",
    "hallucination": "[환각] 환각/허위정보",
    "code_generation": "[코드] 악성 코드 생성",
    "special_tokens": "[토큰] 특수 토큰 공격",
    "web_vulnerability": "[웹] 웹 취약점",
}

# ── 색상 정의 ──
COLOR_RED = (231, 76, 60)
COLOR_ORANGE = (243, 156, 18)
COLOR_GREEN = (46, 204, 113)
COLOR_DARK = (44, 62, 80)
COLOR_GRAY = (149, 165, 166)
COLOR_LIGHT_BG = (245, 245, 245)
COLOR_WHITE = (255, 255, 255)
COLOR_BLUE = (52, 152, 219)


class VromptPDF(FPDF):
    """Vrompt 스캔 리포트용 커스텀 PDF 클래스"""

    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self._setup_fonts()
        self.set_auto_page_break(auto=True, margin=20)

    def _setup_fonts(self):
        """한글 폰트 설정"""
        font_dir = r"C:\Windows\Fonts"
        regular = os.path.join(font_dir, "malgun.ttf")
        bold = os.path.join(font_dir, "malgunbd.ttf")

        if os.path.exists(regular):
            self.add_font("MalgunGothic", "", regular)
        if os.path.exists(bold):
            self.add_font("MalgunGothic", "B", bold)

        # 폰트가 없는 경우 폴백
        if not os.path.exists(regular):
            # DejaVu Sans 시도 (fpdf2 내장)
            pass

    def header(self):
        """페이지 헤더"""
        self.set_font("MalgunGothic", "B", 8)
        self.set_text_color(*COLOR_GRAY)
        self.cell(0, 6, "Vrompt Scan Report", align="L")
        self.cell(0, 6, f"Page {self.page_no()}/{{nb}}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*COLOR_GRAY)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        """페이지 풋터"""
        self.set_y(-15)
        self.set_font("MalgunGothic", "", 7)
        self.set_text_color(*COLOR_GRAY)
        self.cell(0, 8, "Generated by Vrompt", align="C")


def _safe_text(text: str) -> str:
    """PDF에서 표시 불가능한 문자 제거/치환"""
    if not text:
        return "(없음)"

    replacements = {
        '\U0001f170\ufe0f': '[A]', '\U0001f171\ufe0f': '[B]',
        '\U0001f170': '[A]', '\U0001f171': '[B]',
        '\u2705': '[OK]', '\u274c': '[X]',
        '\u26a0\ufe0f': '[!]', '\u26a0': '[!]',
        '\U0001f916': '[AI]', '\U0001f4e8': '[P]',
        '\U0001f4ac': '[R]', '\U0001f4dd': '[M]',
        '\U0001f534': '[!]', '\U0001f7e1': '[?]',
        '\U0001f7e2': '[O]', '\U0001f513': '',
        '\U0001f489': '', '\U0001f511': '',
        '\U0001f4ca': '', '\U0001f9ec': '',
        '\u26a1': '', '\U0001f4bb': '',
        '\U0001f524': '', '\U0001f310': '',
        '\u23f8\ufe0f': '[?]', '\u23f8': '[?]',
        '\U0001f1e6': '[A]', '\U0001f1e7': '[B]',
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    # 일반적인 이모지/특수 유니코드 제거 (BMP 외 문자)
    cleaned = []
    for ch in text:
        code = ord(ch)
        # BMP 범위 내의 대부분 문자 허용 (이모지 등 비BMP 제거)
        if code < 0x10000 and ch not in ('\ufffd',):
            cleaned.append(ch)
        else:
            cleaned.append('?')
    return "".join(cleaned)


def generate_pdf_report(
    results: List[ProbeResult],
    target_url: str,
    output_path: str,
    dry_run: bool = False,
    elapsed_time: float = 0.0,
    chart_dir: str = None,
    chart_base_name: str = None,
) -> str:
    """
    스캔 결과를 단일 PDF 파일로 생성.

    Args:
        results: 스캔 결과 리스트
        target_url: 대상 URL
        output_path: PDF 저장 경로
        dry_run: 드라이런 모드 여부
        elapsed_time: 총 소요 시간
        chart_dir: 차트 이미지 디렉토리
        chart_base_name: 차트 파일 베이스명

    Returns:
        저장된 PDF 파일 경로
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── 통계 집계 ──
    total = len(results)
    vulns = [r for r in results if r.is_vulnerable and not (r.gemini_detail and "최종: 보류" in r.gemini_detail)]
    pending = [r for r in results if r.gemini_detail and "최종: 보류" in r.gemini_detail]
    safe = total - len(vulns) - len(pending)

    # 카테고리별 집계
    categories: Dict[str, Dict] = {}
    for r in results:
        if r.category not in categories:
            categories[r.category] = {"total": 0, "vulnerable": 0, "pending": 0, "safe": 0, "results": []}
        categories[r.category]["total"] += 1
        is_pending = bool(r.gemini_detail and "최종: 보류" in r.gemini_detail)
        if is_pending:
            categories[r.category]["pending"] += 1
        elif r.is_vulnerable:
            categories[r.category]["vulnerable"] += 1
        else:
            categories[r.category]["safe"] += 1
        categories[r.category]["results"].append(r)

    # ── PDF 생성 ──
    pdf = VromptPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ━━━━ 표지 / 요약 ━━━━
    pdf.set_font("MalgunGothic", "B", 22)
    pdf.set_text_color(*COLOR_DARK)
    pdf.cell(0, 15, "Vrompt Scan Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # 메타 정보 박스
    pdf.set_fill_color(*COLOR_LIGHT_BG)
    pdf.set_font("MalgunGothic", "", 10)
    pdf.set_text_color(*COLOR_DARK)

    meta_lines = [
        f"  Scan Date :  {now}",
        f"  Target URL :  {target_url}",
    ]
    if dry_run:
        meta_lines.append("  Mode :  DRY-RUN (no real API calls)")
    if elapsed_time > 0:
        meta_lines.append(f"  Elapsed :  {elapsed_time:.1f}s")
    meta_lines.append(f"  Total Prompts :  {total}")

    for line in meta_lines:
        pdf.cell(0, 7, _safe_text(line), fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── 전체 요약 테이블 ──
    pdf.set_font("MalgunGothic", "B", 14)
    pdf.set_text_color(*COLOR_DARK)
    pdf.cell(0, 10, _safe_text("[ Summary ]"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    determined_total = total - len(pending)
    vuln_rate = (len(vulns) / determined_total * 100) if determined_total > 0 else 0

    # 테이블 헤더
    col_w = [60, 40]
    pdf.set_font("MalgunGothic", "B", 10)
    pdf.set_fill_color(*COLOR_DARK)
    pdf.set_text_color(*COLOR_WHITE)
    pdf.cell(col_w[0], 8, "  Item", fill=True)
    pdf.cell(col_w[1], 8, "  Value", fill=True, new_x="LMARGIN", new_y="NEXT")

    # 테이블 본문
    summary_rows = [
        ("Total prompts", str(total)),
        ("Vulnerable", str(len(vulns))),
        ("Pending", str(len(pending))),
        ("Safe", str(safe)),
        ("Vuln Rate", f"{vuln_rate:.1f}%"),
    ]
    row_colors = [
        COLOR_DARK, COLOR_RED, COLOR_ORANGE, COLOR_GREEN, COLOR_RED if vuln_rate > 0 else COLOR_GREEN,
    ]

    pdf.set_font("MalgunGothic", "", 10)
    for i, (label, value) in enumerate(summary_rows):
        bg = COLOR_WHITE if i % 2 == 0 else COLOR_LIGHT_BG
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*COLOR_DARK)
        pdf.cell(col_w[0], 7, f"  {label}", fill=True)
        pdf.set_text_color(*row_colors[i])
        pdf.set_font("MalgunGothic", "B", 10)
        pdf.cell(col_w[1], 7, f"  {value}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("MalgunGothic", "", 10)

    pdf.ln(5)

    # ── 차트 이미지 삽입 ──
    if chart_dir and chart_base_name:
        pie_path = os.path.join(chart_dir, f"{chart_base_name}_pie.png")
        bar_path = os.path.join(chart_dir, f"{chart_base_name}_bar.png")

        if os.path.exists(pie_path):
            pdf.image(pie_path, x=15, w=80)
            pdf.ln(3)
        if os.path.exists(bar_path):
            pdf.image(bar_path, x=15, w=170)
            pdf.ln(5)

    # ── 카테고리별 요약 테이블 ──
    pdf.add_page()
    pdf.set_font("MalgunGothic", "B", 14)
    pdf.set_text_color(*COLOR_DARK)
    pdf.cell(0, 10, _safe_text("[ Category Overview ]"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    cat_col_w = [50, 22, 22, 22, 22, 30]
    # 헤더
    pdf.set_font("MalgunGothic", "B", 9)
    pdf.set_fill_color(*COLOR_DARK)
    pdf.set_text_color(*COLOR_WHITE)
    for header_text, w in zip(["Category", "Total", "Vuln", "Pending", "Safe", "Vuln Rate"], cat_col_w):
        pdf.cell(w, 7, f" {header_text}", fill=True)
    pdf.ln()

    pdf.set_font("MalgunGothic", "", 9)
    for i, (cat_key, cat_data) in enumerate(categories.items()):
        cat_name = CATEGORY_NAMES_PDF.get(cat_key, cat_key)
        cat_vuln = cat_data["vulnerable"]
        cat_pending = cat_data["pending"]
        cat_safe = cat_data["safe"]
        cat_total = cat_data["total"]
        cat_det = cat_total - cat_pending
        cat_rate = (cat_vuln / cat_det * 100) if cat_det > 0 else 0

        bg = COLOR_WHITE if i % 2 == 0 else COLOR_LIGHT_BG
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*COLOR_DARK)
        pdf.cell(cat_col_w[0], 7, f" {_safe_text(cat_name)}", fill=True)
        pdf.cell(cat_col_w[1], 7, f" {cat_total}", fill=True)

        pdf.set_text_color(*COLOR_RED if cat_vuln > 0 else COLOR_DARK)
        pdf.cell(cat_col_w[2], 7, f" {cat_vuln}", fill=True)

        pdf.set_text_color(*COLOR_ORANGE if cat_pending > 0 else COLOR_DARK)
        pdf.cell(cat_col_w[3], 7, f" {cat_pending}", fill=True)

        pdf.set_text_color(*COLOR_GREEN)
        pdf.cell(cat_col_w[4], 7, f" {cat_safe}", fill=True)

        pdf.set_text_color(*COLOR_RED if cat_rate > 0 else COLOR_GREEN)
        pdf.set_font("MalgunGothic", "B", 9)
        pdf.cell(cat_col_w[5], 7, f" {cat_rate:.0f}%", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("MalgunGothic", "", 9)

    pdf.ln(8)

    # ━━━━ 카테고리별 상세 결과 ━━━━
    for cat_key, cat_data in categories.items():
        cat_name = CATEGORY_NAMES_PDF.get(cat_key, cat_key)

        pdf.add_page()
        pdf.set_font("MalgunGothic", "B", 14)
        pdf.set_text_color(*COLOR_DARK)
        pdf.cell(0, 10, _safe_text(f"[ {cat_name} ]"), new_x="LMARGIN", new_y="NEXT")

        # 카테고리 미니 요약
        cat_vuln = cat_data["vulnerable"]
        cat_pending = cat_data["pending"]
        cat_safe = cat_data["safe"]
        cat_total = cat_data["total"]
        cat_det = cat_total - cat_pending
        cat_rate = (cat_vuln / cat_det * 100) if cat_det > 0 else 0

        pdf.set_font("MalgunGothic", "", 9)
        pdf.set_text_color(*COLOR_GRAY)
        pdf.cell(0, 6,
                 _safe_text(f"Total: {cat_total}  |  Vuln: {cat_vuln}  |  Pending: {cat_pending}  |  Safe: {cat_safe}  |  Rate: {cat_rate:.0f}%"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # 개별 결과
        for i, r in enumerate(cat_data["results"], 1):
            is_pending_item = bool(r.gemini_detail and "최종: 보류" in r.gemini_detail)

            # 남은 공간 체크 — 최소 55mm 필요
            if pdf.get_y() > 230:
                pdf.add_page()

            # 상태 배지
            if is_pending_item:
                status_text = f"#{i} - PENDING"
                badge_color = COLOR_ORANGE
            elif r.is_vulnerable:
                status_text = f"#{i} - VULNERABLE"
                badge_color = COLOR_RED
            else:
                status_text = f"#{i} - SAFE"
                badge_color = COLOR_GREEN

            # 상태 줄
            pdf.set_fill_color(*badge_color)
            pdf.set_text_color(*COLOR_WHITE)
            pdf.set_font("MalgunGothic", "B", 9)
            pdf.cell(0, 6, f"  {status_text}", fill=True, new_x="LMARGIN", new_y="NEXT")

            # 프롬프트
            pdf.set_font("MalgunGothic", "B", 8)
            pdf.set_text_color(*COLOR_DARK)
            pdf.cell(0, 5, "  Prompt:", new_x="LMARGIN", new_y="NEXT")

            prompt_text = r.prompt if len(r.prompt) <= 400 else r.prompt[:400] + "..."
            pdf.set_font("MalgunGothic", "", 8)
            pdf.set_fill_color(*COLOR_LIGHT_BG)
            pdf.set_text_color(*COLOR_DARK)
            pdf.multi_cell(0, 4, _safe_text(f"  {prompt_text}"), fill=True)
            pdf.ln(1)

            # 응답
            pdf.set_font("MalgunGothic", "B", 8)
            pdf.set_text_color(*COLOR_DARK)
            pdf.cell(0, 5, "  Response:", new_x="LMARGIN", new_y="NEXT")

            resp_text = r.response or "(no response)"
            resp_text = resp_text if len(resp_text) <= 500 else resp_text[:500] + "..."
            pdf.set_font("MalgunGothic", "", 8)
            pdf.set_fill_color(240, 248, 255)
            pdf.multi_cell(0, 4, _safe_text(f"  {resp_text}"), fill=True)
            pdf.ln(1)

            # 탐지 사유
            pdf.set_font("MalgunGothic", "", 7)
            pdf.set_text_color(*COLOR_GRAY)
            detection_label = "Detection" if r.is_vulnerable else "Judgement"
            pdf.cell(0, 4, _safe_text(f"  {detection_label}: {r.detection_detail or '-'}"), new_x="LMARGIN", new_y="NEXT")

            # AI 교차 검증
            if r.gemini_detail:
                ai_text = r.gemini_detail
                # 기호 변경 및 들여쓰기 추가
                for emoji in ['\U0001f170\ufe0f', '\U0001f170', '\U0001f1e6']:
                    ai_text = ai_text.replace(f'> {emoji}', f'\n|>[A]')
                for emoji in ['\U0001f171\ufe0f', '\U0001f171', '\U0001f1e7']:
                    ai_text = ai_text.replace(f'> {emoji}', f'\n|>[B]')
                    
                ai_text = ai_text.replace('\n', '\n  ')
                ai_short = ai_text[:800] + ("..." if len(ai_text) > 800 else "")
                
                pdf.set_text_color(*COLOR_DARK)
                pdf.set_fill_color(235, 245, 255)
                pdf.multi_cell(0, 4, _safe_text(f"  AI Verify: {ai_short}"), fill=True)
                pdf.ln(1)

            pdf.cell(0, 4, _safe_text(f"  Response Time: {r.elapsed_time:.2f}s"), new_x="LMARGIN", new_y="NEXT")

            # 구분선
            pdf.set_draw_color(*COLOR_GRAY)
            y = pdf.get_y() + 1
            pdf.line(10, y, 200, y)
            pdf.ln(3)

    # ━━━━ 취약점 요약 ━━━━
    if vulns:
        pdf.add_page()
        pdf.set_font("MalgunGothic", "B", 14)
        pdf.set_text_color(*COLOR_RED)
        pdf.cell(0, 10, _safe_text("[ Vulnerabilities Found ]"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        vuln_col_w = [10, 45, 20, 55, 55]
        pdf.set_font("MalgunGothic", "B", 8)
        pdf.set_fill_color(*COLOR_RED)
        pdf.set_text_color(*COLOR_WHITE)
        for header_text, w in zip(["#", "Category", "Status", "Detection", "Prompt"], vuln_col_w):
            pdf.cell(w, 7, f" {header_text}", fill=True)
        pdf.ln()

        pdf.set_font("MalgunGothic", "", 7)
        for vi, r in enumerate(vulns, 1):
            cat_name_short = CATEGORY_NAMES_PDF.get(r.category, r.category)
            prompt_short = r.prompt[:20].replace("\n", " ")
            if len(r.prompt) > 20:
                prompt_short += "..."
            detail_short = (r.detection_detail or "-")[:20]

            bg = COLOR_WHITE if vi % 2 == 0 else COLOR_LIGHT_BG
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*COLOR_DARK)

            pdf.cell(vuln_col_w[0], 6, f" {vi}", fill=True)
            pdf.cell(vuln_col_w[1], 6, f" {_safe_text(cat_name_short[:25])}", fill=True)
            pdf.set_text_color(*COLOR_RED)
            pdf.cell(vuln_col_w[2], 6, " VULN", fill=True)
            pdf.set_text_color(*COLOR_DARK)
            pdf.cell(vuln_col_w[3], 6, f" {_safe_text(detail_short)}", fill=True)
            pdf.cell(vuln_col_w[4], 6, f" {_safe_text(prompt_short)}", fill=True, new_x="LMARGIN", new_y="NEXT")

            # 페이지 넘김 체크
            if pdf.get_y() > 270:
                pdf.add_page()
                pdf.set_font("MalgunGothic", "B", 8)
                pdf.set_fill_color(*COLOR_RED)
                pdf.set_text_color(*COLOR_WHITE)
                for header_text, w in zip(["#", "Category", "Status", "Detection", "Prompt"], vuln_col_w):
                    pdf.cell(w, 7, f" {header_text}", fill=True)
                pdf.ln()
                pdf.set_font("MalgunGothic", "", 7)

        pdf.ln(5)

    # ━━━━ 권고사항 ━━━━
    pdf.add_page()
    pdf.set_font("MalgunGothic", "B", 14)
    pdf.set_text_color(*COLOR_DARK)
    pdf.cell(0, 10, _safe_text("[ Recommendations ]"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("MalgunGothic", "", 10)
    pdf.set_text_color(*COLOR_DARK)

    if len(vulns) > 0:
        recommendations = [
            "1. [URGENT] Immediately patch all discovered vulnerabilities",
            "2. Strengthen explicit denial instructions in system prompts",
            "3. Add input filtering and output validation layers",
            "4. Apply pre-decoding + filtering for encoded inputs",
            "5. Perform regular vulnerability scans",
        ]
        recommendations_kr = [
            "1. [긴급] 발견된 취약점에 대한 즉시 패치 적용",
            "2. 시스템 프롬프트에 명시적 거부 지침 강화",
            "3. 입력 필터링 및 출력 검증 레이어 추가",
            "4. 인코딩된 입력에 대한 사전 디코딩 + 필터링 적용",
            "5. 정기적인 취약점 스캔 수행",
        ]
        pdf.set_text_color(*COLOR_RED)
        pdf.set_font("MalgunGothic", "B", 10)
        pdf.cell(0, 7, _safe_text("취약점이 발견되었습니다. 다음 조치를 권고합니다:"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("MalgunGothic", "", 9)
        pdf.set_text_color(*COLOR_DARK)
        for rec in recommendations_kr:
            pdf.cell(0, 6, _safe_text(f"  {rec}"), new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_text_color(*COLOR_GREEN)
        pdf.set_font("MalgunGothic", "B", 10)
        pdf.cell(0, 7, _safe_text("현재 스캔 기준으로 취약점이 발견되지 않았습니다."), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("MalgunGothic", "", 9)
        pdf.set_text_color(*COLOR_DARK)
        pdf.cell(0, 6, _safe_text("  정기적인 스캔을 통해 지속적인 모니터링을 권장합니다."), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_font("MalgunGothic", "", 7)
    pdf.set_text_color(*COLOR_GRAY)
    pdf.cell(0, 5, _safe_text(f"Generated by Vrompt at {now}"), align="C")

    # ── 저장 ──
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    pdf.output(output_path)

    return output_path
